### ISSUE TITLE
CUDA OOM during training

### ISSUE THREAD

**Issue by huchinlp** [zalandoresearch/flair#1251]
I got a CUDA OOM error when running the experiment for CoNLL-03 English NER in this page： [https://github.com/zalandoresearch/flair/blob/master/resources/docs/EXPERIMENTS.md](url)

Runtime:
os: centos7
cuda: 9.2
pytorch: 1.3.0+cu92
flair: newest version

Here is the log:
2019-10-29 22:05:23,873 Model training base path: "resources/taggers/example-ner"
2019-10-29 22:05:23,873 ----------------------------------------------------------------------------------------------------
2019-10-29 22:05:23,873 Device: cuda:0
2019-10-29 22:05:23,873 ----------------------------------------------------------------------------------------------------
2019-10-29 22:05:23,873 Embeddings storage mode: cpu
2019-10-29 22:05:23,874 ----------------------------------------------------------------------------------------------------
train mode resetting embeddings
train mode resetting embeddings
2019-10-29 22:05:24,308 epoch 1 - iter 0/577 - loss 71.33390808 - samples/sec: 4207.49
2019-10-29 22:05:48,415 epoch 1 - iter 57/577 - loss 9.48243091 - samples/sec: 75.74
Traceback (most recent call last):
  File "train.py", line 45, in <module>
    max_epochs=150)
  File "/home/huchi/work/acl2020/darts_thinknet/ner/flair/trainers/trainer.py", line 325, in train
    loss.backward()
  File "/home/huchi/anaconda3/envs/ner/lib/python3.6/site-packages/torch/tensor.py", line 150, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/huchi/anaconda3/envs/ner/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 264.00 MiB (GPU 0; 10.92 GiB total capacity; 8.69 GiB already allocated; 129.12 MiB free; 1.50 GiB cached)

**Comment by huchinlp** [comment]
The GPU memory keeps increasing in training iterations.

**Comment by huchinlp** [comment]
Finally, I solved it by rolling back to flair 0.4.2 (0.4.3 also works but it is slower).
