### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by songtaoshi** [zalandoresearch/flair#926]
**Describe the bug**
When I make model in gpu, the bug cuDNN error

**To Reproduce**
I first make a conda environment.by 
[conda create -n flair python=3.7](url)
after activate to the environment, then I install the flair
[pip install flair](url)
then I run my code [python bilstm-crf.py](url)
the code is 
`"""
this is for tagging training
"""

#reading my own sequence labeling dataset
from flair.data import Corpus
from flair.datasets import ColumnCorpus

# define columns
columns = {0: 'text', 1: 'ner'}

# this is the folder in which train, test and dev files reside
data_folder = '../data/model_train'
embedding_file = './pre_train_model/epoch_3.pt'
# init a corpus using column format, data folder and the names of the train, dev and test files
corpus: Corpus = ColumnCorpus(data_folder, columns,
                              train_file='train.txt',
                              test_file='test.txt',
                              dev_file='dev.txt')

from flair.embeddings import OneHotEmbeddings,FlairEmbeddings

# 2. what tag do we want to predict?
tag_type = 'ner'

# 3. make the tag dictionary from the corpus
tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)
print(tag_dictionary.idx2item)

# init embeddings from your trained LM
embeddings = OneHotEmbeddings(corpus)
# embeddings = FlairEmbeddings(embedding_file)

# 5. initialize sequence tagger
from flair.models import SequenceTagger

tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type,
                                        use_crf=True)

# 6. initialize trainer
from flair.trainers import ModelTrainer

trainer: ModelTrainer = ModelTrainer(tagger, corpus)

# 7. start training
trainer.train('resources/taggers/example-ner',
              learning_rate=0.1,
              mini_batch_size=32,
              max_epochs=150,
              embeddings_in_memory=True)

# 8. plot training curves (optional)
from flair.visual.training_curves import Plotter
plotter = Plotter()
plotter.plot_training_curves('resources/taggers/example-ner/loss.tsv')
plotter.plot_weights('resources/taggers/example-ner/weights.txt')`
**Expected behavior**
I expect the program train correctly !

**Screenshots**
![image](https://user-images.githubusercontent.com/20240391/61790532-0834c600-ae4a-11e9-9d62-126c596eb6f5.png)

**Environment (please complete the following information):**
 - OS :ubuntu 18.04
 - Version : flair-0.4.2
![image](https://user-images.githubusercontent.com/20240391/61790576-2bf80c00-ae4a-11e9-8b24-4eedbf976539.png)

**Additional context**
I am really confused how to get the version of cuda and cudnn version in my conda environment.

**Comment by alanakbik** [comment]
Not really sure if this is specific to Flair. This may point to a problen in your CUDA setup and PyTorch version. See https://discuss.pytorch.org/t/runtimeerror-cudnn-error-cudnn-status-execution-failed/31169/7

**Comment by songtaoshi** [comment]
Thanks a lot, How could I get the version of cuda and cudnn version in the conda environment?

**Comment by petasis** [comment]
I have faced exactly the same error, but even in a stranger setting: I could use the second graphics card, but I got the error with the first (of course with the same code).
What I did was to remove pytorch and re-install it again from the matrix they have on pytorch site.
My problem was solved.

**Comment by songtaoshi** [comment]
Thanks a lot. I find the problem. If I use the pip install flair, it will install the pytorch 1.1.0 throngh pip ! but at the same time it will not install cuda and cudnn. However, if I install cuda and cudnn through conda, it won't match. So we should use `pip uninstall pytorch` to uninstall the version without cuda and then we install by  `conda install pytorch cudatoolkit=10.0` . @alanakbik @petasis
